project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('tasks.index');
    //return view('welcome');
});

Route::patch('tasks/{id}/completed',['uses' => 'TaskController@markAsCompleted']);

Route::resource('tasks', 'TaskController');

project/app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    /**
     * Mass Assignment
     */
    protected $guarded = ['id'];


}

project/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

project/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

project/app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $tasks = Task::all();

        return view('tasks', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        dd('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {	
        $details = trim($request->details);
        $task = Task::firstOrCreate(['details' => $details]);

        return response()->json(['details' => $task->details], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        dd('show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        dd('edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $details = trim($request->details);
        
        $task = Task::findOrFail($id);
        $task->details = $details;
        $task->save();

        return response()->json(['details' => $task->details], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        dd('destroy');
    }

    public function markAsCompleted(Request $request, $id){
    	$task = Task::findOrFail($id);
        $task->completed = 1;
        $task->save();

        return response(200);
    }
}

project/resources/views/tasks.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>To Do List</title>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
	<h1>To Do List</h1>
	<h2>Create A Task</h2>
	{{-- <form action="{{route('tasks.store')}}" method="post"> --}}
		<input type="hidden" name="_token" id="token" value="{{csrf_token()}}">
		<input type="text" name="details" id="details">	
		<button onclick="saveTask()">Submit Task</button>
	{{-- </form> --}}
	
	
	<h2>Existing Tasks</h2>
	<div id="tasks">
		@forelse ($tasks as $task)
			<div id="task-{{$task->id}}">
				<span id="details-{{$task->id}}" @if ($task->completed)
					style="text-decoration: line-through;"
				@endif>{{$task->details}}</span> 
				@if (!$task->completed)
					<span id="incomplete-options-{{$task->id}}">
						<button onclick="showEdit({{$task->id}})">Edit</button>
						<button id="completed-{{$task->id}}" onclick="markAsCompleted({{$task->id}})">Completed</button>
					</span>
				@endif
				<br>

				<div id="edit-{{$task->id}}" style="display:none">
					<input type="text" name="task_details" id="input-{{$task->id}}" value="{{$task->details}}"> 
					<button onclick="updateTask({{$task->id}})">Update</button>
				</div>
			</div>


			<br>
		@empty
			<div id="no_task"><em>No Tasks</em></div>
		@endforelse	
	</div>
	
</body>
<script>
	function saveTask(){
		if ($('#details').val()) {
			$.ajax({
				type: 'POST',
				url: location.protocol + "//" + location.hostname + 
		      		(location.port && ":" + location.port) + "/" + "tasks",
		      	data: {
		      		_token : $('#token').val(),
		      		details : $('#details').val()
		      	},
		      	success: function(data){
		      		$('#no_task').hide();
		      		$('#tasks').append(data.details + "<br>");
		      		$('#details').val('');
		      	},
		     	error: function(xhr, status, error){
	            	console.log(error);
		        }
			});		
		}
	}
	
	function showEdit(task_id){
		document.getElementById('edit-' + task_id).style.display = "block";
	}

	function updateTask(task_id){
		if ($('#input-' + task_id).val()) {
			$.ajax({
				type: 'PATCH',
				url: location.protocol + "//" + location.hostname + 
		      		(location.port && ":" + location.port) + "/" + "tasks/" + task_id,
		      	data: {
		      		_token : $('#token').val(),
		      		details : $('#input-' + task_id).val()
		      	},
		      	success: function(data){
		      		$('#details-' + task_id).html(data.details);
		      		document.getElementById('edit-' + task_id).style.display = "none";
		      	},
		     	error: function(xhr, status, error){
	            	console.log(error);
		        }
			});		
		}
	}

	function markAsCompleted(task_id){
		if ($('#input-' + task_id).val()) {
			$.ajax({
				type: 'PATCH',
				url: location.protocol + "//" + location.hostname + 
		      		(location.port && ":" + location.port) + "/" + "tasks/" + task_id + "/completed",
		      	data: {
		      		_token : $('#token').val(),
		      	},
		      	success: function(data){
		      		document.getElementById('details-' + task_id).style.textDecoration = "line-through";
		      		document.getElementById('incomplete-options-' + task_id).style.display = "none";
		      		document.getElementById('edit-' + task_id).style.display = "none";
		      	},
		     	error: function(xhr, status, error){
	            	console.log(error);
		        }
			});		
		}
	}
</script>	
</html>